import type { Car, Review, FAQ } from "@/types/car";

export const MOCK_CARS: Car[] = [
  {
    id: "1",
    slug: "byd-song-plus-dmi-2024",
    brand: "BYD",
    model: "Song Plus DM-i",
    year: 2024,
    price_usd: 22500,
    price_uzs: 283500000,
    body_type: "suv",
    fuel_type: "phev",
    engine_volume: 1.5,
    engine_power: 197,
    transmission: "cvt",
    drivetrain: "fwd",
    mileage: 0,
    color: "Белый",
    description_ru: "BYD Song Plus DM-i — популярный подключаемый гибридный кроссовер с расходом всего 1.5л/100км в гибридном режиме.",
    description_uz: "BYD Song Plus DM-i — gibrid rejimda atigi 1.5l/100km sarflaydigan mashhur plagin-gibrid krossover.",
    description_en: "BYD Song Plus DM-i — a popular plug-in hybrid crossover with fuel consumption of just 1.5L/100km in hybrid mode.",
    images: ["/images/cars/byd-song-plus-1.jpg", "/images/cars/byd-song-plus-2.jpg"],
    thumbnail: "/images/cars/byd-song-plus-1.jpg",
    is_hot_offer: true,
    is_available: true,
    order_position: 1,
    specs: { battery: "18.3 kWh", range_electric: "110 km", range_total: "1200 km" },
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "2",
    slug: "chery-tiggo-8-pro-max-2024",
    brand: "Chery",
    model: "Tiggo 8 Pro Max",
    year: 2024,
    price_usd: 28000,
    price_uzs: 352800000,
    body_type: "suv",
    fuel_type: "petrol",
    engine_volume: 2.0,
    engine_power: 254,
    transmission: "automatic",
    drivetrain: "awd",
    mileage: 0,
    color: "Чёрный",
    description_ru: "Chery Tiggo 8 Pro Max — флагманский 7-местный кроссовер с турбированным двигателем и полным приводом.",
    description_uz: "Chery Tiggo 8 Pro Max — turboli dvigatel va to'liq yurgizuvchili flagman 7 o'rinli krossover.",
    description_en: "Chery Tiggo 8 Pro Max — flagship 7-seater crossover with turbocharged engine and all-wheel drive.",
    images: ["/images/cars/chery-tiggo8-1.jpg"],
    thumbnail: "/images/cars/chery-tiggo8-1.jpg",
    is_hot_offer: true,
    is_available: true,
    order_position: 2,
    specs: { seats: 7, trunk: "193 L" },
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "3",
    slug: "haval-jolion-2024",
    brand: "Haval",
    model: "Jolion",
    year: 2024,
    price_usd: 18500,
    price_uzs: 233100000,
    body_type: "crossover",
    fuel_type: "petrol",
    engine_volume: 1.5,
    engine_power: 150,
    transmission: "cvt",
    drivetrain: "fwd",
    mileage: 0,
    color: "Синий",
    description_ru: "Haval Jolion — стильный компактный кроссовер с богатым оснащением и доступной ценой.",
    description_uz: "Haval Jolion — boy jihozlash va qulay narxga ega zamonaviy ixcham krossover.",
    description_en: "Haval Jolion — a stylish compact crossover with rich equipment and affordable price.",
    images: ["/images/cars/haval-jolion-1.jpg"],
    thumbnail: "/images/cars/haval-jolion-1.jpg",
    is_hot_offer: true,
    is_available: true,
    order_position: 3,
    specs: {},
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "4",
    slug: "geely-monjaro-2024",
    brand: "Geely",
    model: "Monjaro",
    year: 2024,
    price_usd: 32000,
    price_uzs: 403200000,
    body_type: "suv",
    fuel_type: "petrol",
    engine_volume: 2.0,
    engine_power: 238,
    transmission: "automatic",
    drivetrain: "awd",
    mileage: 0,
    color: "Серый",
    description_ru: "Geely Monjaro — премиальный кроссовер с просторным салоном и передовыми технологиями.",
    description_uz: "Geely Monjaro — keng salon va ilg'or texnologiyalarga ega premium krossover.",
    description_en: "Geely Monjaro — premium crossover with spacious interior and cutting-edge technology.",
    images: ["/images/cars/geely-monjaro-1.jpg"],
    thumbnail: "/images/cars/geely-monjaro-1.jpg",
    is_hot_offer: true,
    is_available: true,
    order_position: 4,
    specs: {},
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "5",
    slug: "changan-uni-v-2024",
    brand: "Changan",
    model: "UNI-V",
    year: 2024,
    price_usd: 19000,
    price_uzs: 239400000,
    body_type: "sedan",
    fuel_type: "petrol",
    engine_volume: 1.5,
    engine_power: 188,
    transmission: "automatic",
    drivetrain: "fwd",
    mileage: 0,
    color: "Красный",
    description_ru: "Changan UNI-V — спортивный лифтбек с агрессивным дизайном и мощным турбомотором.",
    description_uz: "Changan UNI-V — agressiv dizayn va kuchli turbomotorga ega sport liftbek.",
    description_en: "Changan UNI-V — sporty liftback with aggressive design and powerful turbo engine.",
    images: ["/images/cars/changan-univ-1.jpg"],
    thumbnail: "/images/cars/changan-univ-1.jpg",
    is_hot_offer: true,
    is_available: true,
    order_position: 5,
    specs: {},
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "6",
    slug: "jetour-dashing-2024",
    brand: "JETOUR",
    model: "Dashing",
    year: 2024,
    price_usd: 21000,
    price_uzs: 264600000,
    body_type: "crossover",
    fuel_type: "petrol",
    engine_volume: 1.5,
    engine_power: 156,
    transmission: "cvt",
    drivetrain: "fwd",
    mileage: 0,
    color: "Белый",
    description_ru: "JETOUR Dashing — современный кроссовер с панорамной крышей и большим багажником.",
    description_uz: "JETOUR Dashing — panoramali tom va katta yukxona bilan zamonaviy krossover.",
    description_en: "JETOUR Dashing — modern crossover with panoramic roof and large trunk.",
    images: ["/images/cars/jetour-dashing-1.jpg"],
    thumbnail: "/images/cars/jetour-dashing-1.jpg",
    is_hot_offer: true,
    is_available: true,
    order_position: 6,
    specs: {},
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "7",
    slug: "zeekr-001-2024",
    brand: "Zeekr",
    model: "001",
    year: 2024,
    price_usd: 45000,
    price_uzs: 567000000,
    body_type: "sedan",
    fuel_type: "electric",
    engine_volume: null,
    engine_power: 544,
    transmission: "automatic",
    drivetrain: "awd",
    mileage: 0,
    color: "Синий",
    description_ru: "Zeekr 001 — премиальный электрический шутинг-брейк с разгоном до 100 за 3.8 секунды.",
    description_uz: "Zeekr 001 — 3.8 soniyada 100 km/soatga yetadigan premium elektr shooting-brake.",
    description_en: "Zeekr 001 — premium electric shooting brake with 0-100 km/h in 3.8 seconds.",
    images: ["/images/cars/zeekr-001-1.jpg"],
    thumbnail: "/images/cars/zeekr-001-1.jpg",
    is_hot_offer: true,
    is_available: true,
    order_position: 7,
    specs: { battery: "100 kWh", range: "656 km", acceleration: "3.8s" },
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "8",
    slug: "li-auto-l7-2024",
    brand: "Li Auto",
    model: "L7",
    year: 2024,
    price_usd: 48000,
    price_uzs: 604800000,
    body_type: "suv",
    fuel_type: "phev",
    engine_volume: 1.5,
    engine_power: 449,
    transmission: "automatic",
    drivetrain: "awd",
    mileage: 0,
    color: "Чёрный",
    description_ru: "Li Auto L7 — роскошный полноразмерный SUV с увеличенным запасом хода и инновационным интерьером.",
    description_uz: "Li Auto L7 — kengaytirilgan masofaga ega hashamatli to'liq o'lchamli SUV.",
    description_en: "Li Auto L7 — luxury full-size SUV with extended range and innovative interior.",
    images: ["/images/cars/li-l7-1.jpg"],
    thumbnail: "/images/cars/li-l7-1.jpg",
    is_hot_offer: true,
    is_available: true,
    order_position: 8,
    specs: { battery: "42.8 kWh", range_electric: "210 km", range_total: "1315 km" },
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "9",
    slug: "exeed-vx-2024",
    brand: "Exeed",
    model: "VX",
    year: 2024,
    price_usd: 35000,
    price_uzs: 441000000,
    body_type: "suv",
    fuel_type: "petrol",
    engine_volume: 2.0,
    engine_power: 249,
    transmission: "automatic",
    drivetrain: "awd",
    mileage: 0,
    color: "Белый",
    description_ru: "Exeed VX — 7-местный премиум-кроссовер от суббренда Chery с роскошной отделкой салона.",
    description_uz: "Exeed VX — Chery sub-brendidan hashamatli ichki bezak bilan 7 o'rinli premium krossover.",
    description_en: "Exeed VX — 7-seater premium crossover from Chery's sub-brand with luxurious interior.",
    images: ["/images/cars/exeed-vx-1.jpg"],
    thumbnail: "/images/cars/exeed-vx-1.jpg",
    is_hot_offer: true,
    is_available: true,
    order_position: 9,
    specs: { seats: 7 },
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "10",
    slug: "tank-300-2024",
    brand: "Tank",
    model: "300",
    year: 2024,
    price_usd: 38000,
    price_uzs: 478800000,
    body_type: "suv",
    fuel_type: "petrol",
    engine_volume: 2.0,
    engine_power: 220,
    transmission: "automatic",
    drivetrain: "awd",
    mileage: 0,
    color: "Зелёный",
    description_ru: "Tank 300 — настоящий рамный внедорожник с ретро-дизайном и серьёзными внедорожными способностями.",
    description_uz: "Tank 300 — retro dizayn va jiddiy yo'lsizlik qobiliyatlariga ega haqiqiy ramali SUV.",
    description_en: "Tank 300 — a true body-on-frame SUV with retro design and serious off-road capabilities.",
    images: ["/images/cars/tank-300-1.jpg"],
    thumbnail: "/images/cars/tank-300-1.jpg",
    is_hot_offer: true,
    is_available: true,
    order_position: 10,
    specs: {},
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "11",
    slug: "byd-han-ev-2024",
    brand: "BYD",
    model: "Han EV",
    year: 2024,
    price_usd: 35000,
    price_uzs: 441000000,
    body_type: "sedan",
    fuel_type: "electric",
    engine_volume: null,
    engine_power: 517,
    transmission: "automatic",
    drivetrain: "awd",
    mileage: 0,
    color: "Серебристый",
    description_ru: "BYD Han EV — флагманский электрический седан с запасом хода до 610 км и разгоном до 100 за 3.9с.",
    description_uz: "BYD Han EV — 610 km masofaga va 3.9 soniyada 100 km/soatga yetadigan flagman elektr sedan.",
    description_en: "BYD Han EV — flagship electric sedan with up to 610 km range and 0-100 in 3.9s.",
    images: ["/images/cars/byd-han-1.jpg"],
    thumbnail: "/images/cars/byd-han-1.jpg",
    is_hot_offer: true,
    is_available: true,
    order_position: 11,
    specs: { battery: "85.4 kWh", range: "610 km", acceleration: "3.9s" },
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
  {
    id: "12",
    slug: "omoda-c5-2024",
    brand: "Omoda",
    model: "C5",
    year: 2024,
    price_usd: 17500,
    price_uzs: 220500000,
    body_type: "crossover",
    fuel_type: "petrol",
    engine_volume: 1.5,
    engine_power: 147,
    transmission: "cvt",
    drivetrain: "fwd",
    mileage: 0,
    color: "Белый",
    description_ru: "Omoda C5 — молодёжный кроссовер с ярким дизайном и отличным соотношением цены и качества.",
    description_uz: "Omoda C5 — yorqin dizayn va narx-sifat nisbati bilan ajoyib yoshlar krossoveri.",
    description_en: "Omoda C5 — youthful crossover with vibrant design and excellent value for money.",
    images: ["/images/cars/omoda-c5-1.jpg"],
    thumbnail: "/images/cars/omoda-c5-1.jpg",
    is_hot_offer: true,
    is_available: true,
    order_position: 12,
    specs: {},
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
  },
];

export const MOCK_REVIEWS: Review[] = [
  {
    id: "1",
    client_name: "Алишер М.",
    car_description: "BYD Song Plus DM-i 2024",
    review_text_ru: "Отличный сервис! Машину доставили за 30 дней, все документы в порядке. Рекомендую Tez Motors!",
    review_text_uz: "Ajoyib xizmat! Mashinani 30 kun ichida yetkazib berishdi, barcha hujjatlar tartibda. Tez Motorsni tavsiya qilaman!",
    review_text_en: "Excellent service! Car delivered in 30 days, all documents in order. I recommend Tez Motors!",
    photo_url: null,
    video_url: null,
    rating: 5,
    is_published: true,
    order_position: 1,
    car_id: null,
    created_at: "2024-06-15T00:00:00Z",
  },
  {
    id: "2",
    client_name: "Дмитрий К.",
    car_description: "Haval Jolion 2024",
    review_text_ru: "Второй раз заказываю через Tez Motors. Быстро, надёжно и цены ниже, чем у конкурентов.",
    review_text_uz: "Ikkinchi marta Tez Motors orqali buyurtma beraman. Tez, ishonchli va narxlar raqobatchilarnikidan past.",
    review_text_en: "Second time ordering through Tez Motors. Fast, reliable, and prices lower than competitors.",
    photo_url: null,
    video_url: null,
    rating: 5,
    is_published: true,
    order_position: 2,
    car_id: null,
    created_at: "2024-07-20T00:00:00Z",
  },
  {
    id: "3",
    client_name: "Нодира Р.",
    car_description: "Chery Tiggo 8 Pro Max 2024",
    review_text_ru: "Очень довольна! Менеджер всё подробно объяснил, помог с выбором. Машина в идеальном состоянии.",
    review_text_uz: "Juda mamnunman! Menejer hamma narsani batafsil tushuntirdi, tanlashda yordam berdi. Mashina ideal holatda.",
    review_text_en: "Very satisfied! Manager explained everything in detail, helped with the choice. Car in perfect condition.",
    photo_url: null,
    video_url: null,
    rating: 5,
    is_published: true,
    order_position: 3,
    car_id: null,
    created_at: "2024-08-10T00:00:00Z",
  },
  {
    id: "4",
    client_name: "Бахтиёр С.",
    car_description: "Tank 300 2024",
    review_text_ru: "Tank 300 — мечта! Ребята из Tez Motors помогли сэкономить значительную сумму по сравнению с местными дилерами.",
    review_text_uz: "Tank 300 — orzu! Tez Motors yigitlari mahalliy dilerlar bilan solishtirganda katta miqdorda tejashga yordam berishdi.",
    review_text_en: "Tank 300 — a dream! The Tez Motors team helped save a significant amount compared to local dealers.",
    photo_url: null,
    video_url: null,
    rating: 5,
    is_published: true,
    order_position: 4,
    car_id: null,
    created_at: "2024-09-05T00:00:00Z",
  },
];

export const MOCK_FAQS: FAQ[] = [
  {
    id: "1",
    question_ru: "Сколько времени занимает доставка автомобиля из Китая?",
    question_uz: "Xitoydan avtomobilni yetkazib berish qancha vaqt oladi?",
    question_en: "How long does it take to deliver a car from China?",
    answer_ru: "Доставка автомобиля из Китая в Узбекистан занимает от 25 до 45 дней в зависимости от способа доставки (морем, по железной дороге или автовозом) и наличия автомобиля на складе.",
    answer_uz: "Xitoydan O'zbekistonga avtomobilni yetkazib berish 25 dan 45 kungacha vaqt oladi, bu yetkazib berish usuli (dengiz, temir yo'l yoki avtovozyol) va avtomobilning omborda mavjudligiga bog'liq.",
    answer_en: "Delivery of a car from China to Uzbekistan takes 25 to 45 days depending on the delivery method (by sea, rail, or car carrier) and vehicle availability.",
    category: "delivery",
    order_position: 1,
    is_published: true,
  },
  {
    id: "2",
    question_ru: "Какие документы нужны для растаможки автомобиля?",
    question_uz: "Avtomobilni bojxonadan o'tkazish uchun qanday hujjatlar kerak?",
    question_en: "What documents are needed for customs clearance?",
    answer_ru: "Для растаможки вам потребуются: паспорт, ИНН, договор купли-продажи, инвойс, коносамент, сертификат соответствия. Мы берём на себя оформление всех необходимых документов.",
    answer_uz: "Bojxona rasmiylashtiruvi uchun sizga kerak: pasport, STIR, oldi-sotdi shartnomasi, invoys, konosament, muvofiqlik sertifikati. Biz barcha zarur hujjatlarni rasmiylashtirish ishlarini o'z zimmamizga olamiz.",
    answer_en: "For customs clearance you'll need: passport, tax ID, purchase agreement, invoice, bill of lading, conformity certificate. We handle all necessary document processing.",
    category: "customs",
    order_position: 2,
    is_published: true,
  },
  {
    id: "3",
    question_ru: "Можно ли проверить автомобиль перед покупкой?",
    question_uz: "Sotib olishdan oldin avtomobilni tekshirish mumkinmi?",
    question_en: "Can I inspect the car before purchase?",
    answer_ru: "Да! Мы предоставляем подробный фото/видео отчёт автомобиля, результаты диагностики и историю обслуживания. Также возможна видеосвязь с нашим специалистом прямо на площадке.",
    answer_uz: "Ha! Biz avtomobilning batafsil foto/video hisobotini, diagnostika natijalarini va xizmat ko'rsatish tarixini taqdim etamiz. Shuningdek, to'g'ridan-to'g'ri maydonda mutaxassisimiz bilan videoaloqa qilish mumkin.",
    answer_en: "Yes! We provide detailed photo/video reports, diagnostic results, and service history. Video calls with our specialist at the site are also available.",
    category: "purchase",
    order_position: 3,
    is_published: true,
  },
  {
    id: "4",
    question_ru: "Какой размер предоплаты?",
    question_uz: "Oldindan to'lov miqdori qancha?",
    question_en: "What is the deposit amount?",
    answer_ru: "Предоплата составляет 30% от стоимости автомобиля. Остальная сумма вносится после прибытия автомобиля в Узбекистан и прохождения таможенного оформления.",
    answer_uz: "Oldindan to'lov avtomobil narxining 30% ni tashkil qiladi. Qolgan summa avtomobil O'zbekistonga yetib kelgandan va bojxona rasmiylashtiruvi o'tkazilgandan keyin to'lanadi.",
    answer_en: "The deposit is 30% of the car's price. The remaining amount is paid after the car arrives in Uzbekistan and completes customs clearance.",
    category: "payment",
    order_position: 4,
    is_published: true,
  },
  {
    id: "5",
    question_ru: "Предоставляете ли вы гарантию на автомобиль?",
    question_uz: "Avtomobilga kafolat berasizmi?",
    question_en: "Do you provide a warranty on the car?",
    answer_ru: "Да, мы предоставляем гарантию 1 год или 20 000 км на техническое состояние автомобиля. Перед передачей каждый автомобиль проходит полную диагностику.",
    answer_uz: "Ha, biz avtomobilning texnik holatiga 1 yil yoki 20 000 km kafolat beramiz. Topshirishdan oldin har bir avtomobil to'liq diagnostikadan o'tadi.",
    answer_en: "Yes, we provide a 1-year or 20,000 km warranty on the vehicle's technical condition. Every car undergoes full diagnostics before handover.",
    category: "warranty",
    order_position: 5,
    is_published: true,
  },
];
