import { NextRequest, NextResponse } from "next/server";
import { assertCron } from "@/lib/cron/guard";
import { createServiceClient } from "@/lib/supabase/service";
import { gatherMarketingSignals } from "@/lib/marketing-autopilot-data";
import { buildMarketingSuggestions } from "@/lib/marketing-autopilot";
import { generateMarketingContent } from "@/lib/marketing-content";
import { sendDealerDigest } from "@/lib/cron/dealer-digest";
import { reportServerError, logEvent } from "@/lib/error-report";

/**
 * Marketing Autopilot cron — weekly, pre-fills the Content Studio with timely
 * drafts so a one-person dealer never faces a blank page. It DRAFTS only (never
 * auto-publishes): the dealer reviews, edits, then posts or schedules. Dedupes
 * against drafts created in the last 14 days so re-runs don't pile up. Per-run
 * cap bounds LLM spend. Fail-open.
 */
const PER_RUN_CAP = 3;
const DEDUPE_DAYS = 14;

async function handle(request: NextRequest) {
  const unauth = assertCron(request);
  if (unauth) return unauth;

  try {
    const supabase = createServiceClient();
    const signals = await gatherMarketingSignals(supabase);
    const suggestions = buildMarketingSuggestions(signals);

    // Dedupe against recent drafts: same car+kind, or same subject for topic posts.
    const since = new Date(Date.now() - DEDUPE_DAYS * 86_400_000).toISOString();
    const { data: recent } = await supabase
      .from("content_drafts")
      .select("car_id, kind, subject")
      .gte("created_at", since)
      .limit(500);
    const seenCarKind = new Set((recent || []).filter((d) => d.car_id).map((d) => `${d.car_id}:${d.kind}`));
    const seenSubject = new Set((recent || []).map((d) => (d.subject || "").trim().toLowerCase()).filter(Boolean));

    const fresh = suggestions.filter((s) =>
      s.carId ? !seenCarKind.has(`${s.carId}:${s.kind}`) : !seenSubject.has(s.subjectLabel.trim().toLowerCase()),
    );

    let drafted = 0;
    const labels: string[] = [];
    for (const s of fresh.slice(0, PER_RUN_CAP)) {
      let car = null;
      if (s.carId) {
        const { data } = await supabase
          .from("cars")
          .select("brand, model, year, price_usd, body_type, fuel_type")
          .eq("id", s.carId)
          .maybeSingle();
        car = data;
      }
      const { text } = await generateMarketingContent(s.kind, s.locale, { car, topic: s.topic, tone: s.tone });
      const { error } = await supabase
        .from("content_drafts")
        .insert({ kind: s.kind, locale: s.locale, subject: s.subjectLabel, car_id: s.carId, body: text });
      if (!error) {
        drafted += 1;
        labels.push(`${s.kind}: ${s.subjectLabel}`);
      }
    }

    if (drafted > 0) {
      await sendDealerDigest(
        `📣 ${drafted} marketing draft${drafted === 1 ? "" : "s"} ready for review`,
        ["Generated by Marketing Autopilot — review, edit and schedule in Content Studio:", "", ...labels.map((l) => `• ${l}`)],
      );
    }

    logEvent("cron.marketing_autopilot", { suggestions: suggestions.length, fresh: fresh.length, drafted });
    return NextResponse.json({ ok: true, drafted, candidates: fresh.length });
  } catch (error) {
    reportServerError("GET /api/cron/marketing-autopilot", error).catch(() => {});
    return NextResponse.json({ ok: false, error: "Internal error" }, { status: 500 });
  }
}

export const GET = handle;
export const POST = handle;
