-- Phase: CRM sales tasks & follow-up engine.
--
-- A per-salesperson task queue. Tasks are created manually OR auto-generated by
-- /api/cron/generate-tasks from signals that need a human touch (stale new
-- leads, abandoned deposits, hot AI handoffs, due follow-up dates). Linked to
-- the Customer 360 by the 9-digit phone core. Service-role only (RLS on, no
-- policies), mirroring inquiries/orders.
CREATE TABLE IF NOT EXISTS public.crm_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  kind TEXT NOT NULL DEFAULT 'manual'
    CHECK (kind IN ('follow_up', 'call', 'message', 'stale_lead', 'abandoned_deposit', 'handoff', 'review', 'manual')),
  customer_key TEXT,            -- 9-digit phone core → Customer 360
  customer_phone TEXT,
  customer_name TEXT,
  inquiry_id UUID,
  order_id UUID,
  thread_id TEXT,
  assigned_to UUID REFERENCES public.admin_users(id) ON DELETE SET NULL,
  due_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'done', 'snoozed')),
  notes TEXT,
  auto_source TEXT,             -- dedupe key for auto-generated tasks
  created_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ
);

-- One open task per auto-source (so the cron is idempotent).
CREATE UNIQUE INDEX IF NOT EXISTS uniq_crm_tasks_auto_source
  ON public.crm_tasks (auto_source) WHERE auto_source IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_crm_tasks_queue ON public.crm_tasks (status, due_at);
CREATE INDEX IF NOT EXISTS idx_crm_tasks_assignee ON public.crm_tasks (assigned_to, status);

ALTER TABLE public.crm_tasks ENABLE ROW LEVEL SECURITY;
-- No policies on purpose: service-role only.
